version: '3.8'

services:
  # frontend:
  #   build: ./nginx
  #   container_name: nginx_frontend
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - backend
  #   volumes:
  #     - ./nginx/html:/usr/share/nginx/html:ro
  #     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  #     - ./nginx/proxy_params:/etc/nginx/proxy_params:ro
  backend:
    build: ./app_flask
    container_name: flask_backend
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
    expose:
      - "5001"
    ports:
      - 5001:5001
    volumes:
      - ./app_flask:/app

  db:
    image: mysql:5.7
    platform: linux/amd64
    container_name: mysql_db
    environment:
      - MYSQL_DATABASE=mydatabase
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=mypassword
      - MYSQL_ROOT_PASSWORD=rootpassword
      - TZ="Asia/Taipei"
      - PYTHONPATH=/app
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: ['--default-authentication-plugin=mysql_native_password', '--default-time-zone=+08:00']

  test:
    build: ./app_flask
    container_name: flask_test
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
      - PYTHONPATH=/app
    depends_on:
      - db
    volumes:
      - ./app_flask:/app
    command: pytest --cov=app --cov-report=html --html=report.html

volumes:
  db_data: